### ISSUE TITLE
NoSuchMethodError: getRunnerAnnotations()

### ISSUE THREAD

**Issue by piotrturski** [piotrturski/zohhak-migration-test#1]
_From [mdg.cov...@gmail.com](https://code.google.com/u/116667884595374242932/) on June 06, 2013 15:58:37_

Hi,

I get the following error using zohhak.

java.lang.NoSuchMethodError: com.googlecode.zohhak.api.runners.ZohhakRunner.getRunnerAnnotations()[Ljava/lang/annotation/Annotation;
	at com.googlecode.zohhak.api.runners.ZohhakRunner.getDescription(ZohhakRunner.java:49)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:232)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:35)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:115)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

Do you have any idea why?

Cheers

Martin

_Original issue: http://code.google.com/p/zohhak/issues/detail?id=1_

**Comment by piotrturski** [comment]
_From [mdg.cov...@gmail.com](https://code.google.com/u/116667884595374242932/) on June 06, 2013 07:02:16_

Hi again,

I'm using JUnit 4.11 btw.

/Martin

**Comment by piotrturski** [comment]
_From [bastien....@gmail.com](https://code.google.com/u/118343128225743150217/) on September 01, 2013 15:09:12_

Hello,

I ran into the very same exception, and I fixed this using Junit 4.11. I was using an older version of Junit (4.8.2) and changing it solved the problem.

The method getRunnerAnnotations only appears on the version 4.10 of Junit, so my guess would be that you're not really using Junit 4.11.

This is probably more a classpath issue and has very likely nothing to do with Zohhak. If you are using maven, you may want to make sure that Junit 4.11 is really the version that is used.

Hope this helps.

Cheers.

Bastien

**Comment by piotrturski** [comment]
_From [Piotr.Tu...@gmail.com](https://code.google.com/u/106227458016791646508/) on September 30, 2013 14:30:01_

it came out that i use some api introduced in junit 4.10. if you really can reproduce this error with junit 4.11 then plz send me the whole maven project or link to github project. with 4.8.2 and 4.9 i can reproduce this, but with 4.10 and 4.11

**Status:** Accepted

**Comment by piotrturski** [comment]
_From [Piotr.Tu...@gmail.com](https://code.google.com/u/106227458016791646508/) on October 01, 2013 17:03:56_

fixed in 1.0.1

**Status:** Fixed
